# Generated by Django 5.1.7 on 2025-03-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userimage',
            unique_together={('user', 'image_name')},
        ),
    ]
